/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppListingsIndexRouteImport } from './routes/_app/listings/index'
import { Route as AppListingsAddRouteImport } from './routes/_app/listings/add'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminVendorsRouteImport } from './routes/_admin/vendors'
import { Route as AdminApprovalsRouteImport } from './routes/_admin/approvals'
import { Route as AdminBusinessesRouteImport } from './routes/_admin/businesses'
import { Route as AdminCategoriesRouteImport } from './routes/_admin/categories'
import { Route as AdminDocumentsRouteImport } from './routes/_admin/documents'
import { Route as AdminNotificationsRouteImport } from './routes/_admin/notifications'
import { Route as AdminReportsRouteImport } from './routes/_admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminProfileRouteImport } from './routes/_admin/profile'

const RegisterRoute = RegisterRouteImport.update({ id: '/register', path: '/register', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const AppRoute = AppRouteImport.update({ id: '/_app', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/_admin', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

const AppSettingsRoute = AppSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AppRoute } as any)
const AppProfileRoute = AppProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => AppRoute } as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => AppRoute } as any)
const AppGalleryRoute = AppGalleryRouteImport.update({ id: '/gallery', path: '/gallery', getParentRoute: () => AppRoute } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AppRoute } as any)
const AppListingsIndexRoute = AppListingsIndexRouteImport.update({ id: '/listings/', path: '/listings/', getParentRoute: () => AppRoute } as any)
const AppListingsAddRoute = AppListingsAddRouteImport.update({ id: '/listings/add', path: '/listings/add', getParentRoute: () => AppRoute } as any)

const AdminDashboardRoute = AdminDashboardRouteImport.update({ id: '/dashboard', path: '/admin/dashboard', getParentRoute: () => AdminRoute } as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({ id: '/vendors', path: '/admin/vendors', getParentRoute: () => AdminRoute } as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({ id: '/approvals', path: '/admin/approvals', getParentRoute: () => AdminRoute } as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({ id: '/businesses', path: '/admin/businesses', getParentRoute: () => AdminRoute } as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({ id: '/categories', path: '/admin/categories', getParentRoute: () => AdminRoute } as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({ id: '/documents', path: '/admin/documents', getParentRoute: () => AdminRoute } as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({ id: '/notifications', path: '/admin/notifications', getParentRoute: () => AdminRoute } as any)
const AdminReportsRoute = AdminReportsRouteImport.update({ id: '/reports', path: '/admin/reports', getParentRoute: () => AdminRoute } as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({ id: '/settings', path: '/admin/settings', getParentRoute: () => AdminRoute } as any)
const AdminProfileRoute = AdminProfileRouteImport.update({ id: '/profile', path: '/admin/profile', getParentRoute: () => AdminRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/gallery': typeof AppGalleryRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/listings/add': typeof AppListingsAddRoute
  '/listings/': typeof AppListingsIndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/profile': typeof AdminProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/gallery': typeof AppGalleryRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/listings/add': typeof AppListingsAddRoute
  '/listings': typeof AppListingsIndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/profile': typeof AdminProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/listings/add': typeof AppListingsAddRoute
  '/_app/listings/': typeof AppListingsIndexRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/vendors': typeof AdminVendorsRoute
  '/_admin/approvals': typeof AdminApprovalsRoute
  '/_admin/businesses': typeof AdminBusinessesRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/documents': typeof AdminDocumentsRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/reports': typeof AdminReportsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/profile': typeof AdminProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/gallery'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/listings/add'
    | '/listings/'
    | '/admin/dashboard'
    | '/admin/vendors'
    | '/admin/approvals'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/gallery'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/listings/add'
    | '/listings'
    | '/admin/dashboard'
    | '/admin/vendors'
    | '/admin/approvals'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_admin'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/gallery'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/listings/add'
    | '/_app/listings/'
    | '/_admin/dashboard'
    | '/_admin/vendors'
    | '/_admin/approvals'
    | '/_admin/businesses'
    | '/_admin/categories'
    | '/_admin/documents'
    | '/_admin/notifications'
    | '/_admin/reports'
    | '/_admin/settings'
    | '/_admin/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': { id: '/register'; path: '/register'; fullPath: '/register'; preLoaderRoute: typeof RegisterRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/_app': { id: '/_app'; path: ''; fullPath: '/'; preLoaderRoute: typeof AppRouteImport; parentRoute: typeof rootRouteImport }
    '/_admin': { id: '/_admin'; path: ''; fullPath: '/'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_app/settings': { id: '/_app/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AppSettingsRouteImport; parentRoute: typeof AppRoute }
    '/_app/profile': { id: '/_app/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof AppProfileRouteImport; parentRoute: typeof AppRoute }
    '/_app/notifications': { id: '/_app/notifications'; path: '/notifications'; fullPath: '/notifications'; preLoaderRoute: typeof AppNotificationsRouteImport; parentRoute: typeof AppRoute }
    '/_app/gallery': { id: '/_app/gallery'; path: '/gallery'; fullPath: '/gallery'; preLoaderRoute: typeof AppGalleryRouteImport; parentRoute: typeof AppRoute }
    '/_app/dashboard': { id: '/_app/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AppDashboardRouteImport; parentRoute: typeof AppRoute }
    '/_app/listings/': { id: '/_app/listings/'; path: '/listings'; fullPath: '/listings/'; preLoaderRoute: typeof AppListingsIndexRouteImport; parentRoute: typeof AppRoute }
    '/_app/listings/add': { id: '/_app/listings/add'; path: '/listings/add'; fullPath: '/listings/add'; preLoaderRoute: typeof AppListingsAddRouteImport; parentRoute: typeof AppRoute }
    '/_admin/dashboard': { id: '/_admin/dashboard'; path: '/admin/dashboard'; fullPath: '/admin/dashboard'; preLoaderRoute: typeof AdminDashboardRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/vendors': { id: '/_admin/vendors'; path: '/admin/vendors'; fullPath: '/admin/vendors'; preLoaderRoute: typeof AdminVendorsRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/approvals': { id: '/_admin/approvals'; path: '/admin/approvals'; fullPath: '/admin/approvals'; preLoaderRoute: typeof AdminApprovalsRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/businesses': { id: '/_admin/businesses'; path: '/admin/businesses'; fullPath: '/admin/businesses'; preLoaderRoute: typeof AdminBusinessesRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/categories': { id: '/_admin/categories'; path: '/admin/categories'; fullPath: '/admin/categories'; preLoaderRoute: typeof AdminCategoriesRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/documents': { id: '/_admin/documents'; path: '/admin/documents'; fullPath: '/admin/documents'; preLoaderRoute: typeof AdminDocumentsRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/notifications': { id: '/_admin/notifications'; path: '/admin/notifications'; fullPath: '/admin/notifications'; preLoaderRoute: typeof AdminNotificationsRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/reports': { id: '/_admin/reports'; path: '/admin/reports'; fullPath: '/admin/reports'; preLoaderRoute: typeof AdminReportsRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/settings': { id: '/_admin/settings'; path: '/admin/settings'; fullPath: '/admin/settings'; preLoaderRoute: typeof AdminSettingsRouteImport; parentRoute: typeof AdminRoute }
    '/_admin/profile': { id: '/_admin/profile'; path: '/admin/profile'; fullPath: '/admin/profile'; preLoaderRoute: typeof AdminProfileRouteImport; parentRoute: typeof AdminRoute }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppListingsAddRoute: typeof AppListingsAddRoute
  AppListingsIndexRoute: typeof AppListingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute,
  AppGalleryRoute,
  AppNotificationsRoute,
  AppProfileRoute,
  AppSettingsRoute,
  AppListingsAddRoute,
  AppListingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminProfileRoute: typeof AdminProfileRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute,
  AdminVendorsRoute,
  AdminApprovalsRoute,
  AdminBusinessesRoute,
  AdminCategoriesRoute,
  AdminDocumentsRoute,
  AdminNotificationsRoute,
  AdminReportsRoute,
  AdminSettingsRoute,
  AdminProfileRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute,
  RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
